### ISSUE TITLE
make: *** [Makefile.common:198: common-build] Error 1

### ISSUE THREAD

**Issue by pgloader** [prometheus-community/postgres_exporter#704] opened 2022-10-13 15:01 UTC
**What did you do?**

Trying to build  postgres_exporter

**What did you expect to see?**

Build the application

**What did you see instead? Under which circumstances?**

$ make build
>> building binaries
/home/postgres/go/bin/promu build --prefix /home/postgres/go/src/github.com/prometheus-community/postgres_exporter
 >   postgres_exporter
go: github.com/blang/semver/v4@v4.0.0: Get https://proxy.golang.org/github.com/blang/semver/v4/@v/v4.0.0.mod: proxyconnect tcp: read tcp 10.3.93.38:43680->10.3.79.132:8080: read: connection reset by peer
!! command failed: build -o /home/postgres/go/src/github.com/prometheus-community/postgres_exporter/postgres_exporter -ldflags -X github.com/prometheus/common/version.Version=0.12.0-rc.0 -X github.com/prometheus/common/version.Revision=0adab051b3db7b11ffc26d5b88eddfc0f603d67a -X github.com/prometheus/common/version.Branch=master -X github.com/prometheus/common/version.BuildUser=postgres@rv-poc-zzmwdb-01 -X github.com/prometheus/common/version.BuildDate=20221013-14:48:59  -extldflags '-static' -a -tags 'netgo static_build' github.com/prometheus-community/postgres_exporter/cmd/postgres_exporter: exit status 1
make: *** [Makefile.common:198: common-build] Error 1

**Environment**

Red Hat Enterprise Linux release 8.2 (Ootpa)

* System information:

	 $ uname -srm
Linux 4.18.0-193.14.3.el8_2.x86_64 x86_64

* postgres_exporter version:

	0.12.0-rc.0

* postgres_exporter flags:

```
insert list of flags used here
```

* PostgreSQL version:

	14.2

* Logs:
```
insert logs relevant to the issue here
```

**Comment by sysadmind** [comment] 2022-10-18 00:00
Dupe of #701

**Closed by sysadmind** 2022-10-18 00:00 UTC
