### ISSUE TITLE
Binary has an incorrect version in 0.9.0

### ISSUE THREAD

**Issue by michael-todorovic** [prometheus-community/postgres_exporter#532] opened 2021-05-12 06:49 UTC
**What did you do?**
I tried to get the binary version
```bash
$ curl -LO https://github.com/prometheus-community/postgres_exporter/releases/download/v0.9.0/postgres_exporter-0.9.0.linux-amd64.tar.gz
$ tar xf postgres_exporter-0.9.0.linux-amd64.tar.gz
$ postgres_exporter-0.9.0.linux-amd64/postgres_exporter --version
postgres_exporter 0.0.1-rev (built with go1.15.8)
```

**What did you expect to see?**
I expected the displayed version to be 0.9.0

**What did you see instead? Under which circumstances?**
I got version 0.0.1 for the 0.9.0 build

**Environment**

* System information: 
Linux 5.10.0-0.bpo.5-amd64 x86_64

* postgres_exporter version:
0.9.0

**Comment by SuperQ** [comment] 2021-05-12 07:05
Duplicate of https://github.com/prometheus-community/postgres_exporter/issues/492

**Closed by SuperQ** 2021-05-12 07:05 UTC
Labels: duplicate
